//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitiesAndRoads.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Road
    {
        public int Id { get; set; }
        public int Length { get; set; }
        public int SideCityOneId { get; set; }
        public int SideCityTwoId { get; set; }
    
        public virtual City SideCityOne { get; set; }
        public virtual City SideCityTwo { get; set; }
    }
}
